source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'


gem 'rails', '~> 6.0.4', '>= 6.0.4.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'bootsnap', '>= 1.4.2', require: false
gem "array_enum", "~> 1.3"
gem "rack-cors", "~> 1.1"
gem "graphql", "~> 1.12"
gem "graphql-batch", "~> 0.4.3"

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 5.0"
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :test do
  gem "factory_bot_rails", "~> 6.2"
  gem "shoulda-matchers", "~> 5.0"
  gem "faker", "~> 2.19"
  gem "database_cleaner", "~> 2.0"
  gem "json-schema", "~> 2.8"
end
